version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: modern-task-manager_user
      POSTGRES_PASSWORD: modern-task-manager_password
      POSTGRES_DB: modern-task-manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: