version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: taskmanager-jwt_user
      POSTGRES_PASSWORD: taskmanager-jwt_password
      POSTGRES_DB: taskmanager-jwt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: