version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: task-manager-app_user
      POSTGRES_PASSWORD: task-manager-app_password
      POSTGRES_DB: task-manager-app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: