name: ci
on:
  workflow_dispatch:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Backend
        run: |
          if [ -d backend ]; then cd backend && npm ci || true && npm run build || true; fi
      - name: Frontend
        run: |
          if [ -d frontend ]; then cd frontend && npm ci || true && npm run build || true; fi
